print("*** Calculadora de Média e Verificação  ****")
#IMAGINE QUE VOCÊ ESTÁ CRIANDO UM PEQUENO PROGRAMA PARA CALCULAR A MÉDIA DE UM ALUNO E VERIFICAR SE ELE FOI APROVADO.
#INSTRUÇÕES:
# 1º CRIE TRÊS VARIÁRIAVEIS: nota1,nota2, e nota3.  ATRIBUA A ELAS VALORES NUMÉRICOS (AS NOTAS DO ALUNOS).POR EXEMPLO,7,5 8.0 E 6,5.
# 2º CALCULE A MÉDIA: CRIE UMA VARIAVEL CHAMADA media. USE OS OPERADORES ARITMÉTICOS(+E/)PARA CALCULAR A MÉDIA DAS TRÊS NOTAS E ARMAZENE O RESULTADO EM media.
# 3º VERIFIQUE A APROVAÇÃO É 7.0. CRIE UMA VARIÁVEL CHAMADA aprovado. O VALOR DELA DEVE SER TRUE SE A MEDIA FOR MAIOR OU IGUAL A 7.0, E FALSE CASO CONTRÁRIO. USE UM OPERADOR DE COMPARAÇÃO PARA ISSO.
# 4º IMPRIMA OS RESULTADOS:MOSTRE NO TERMINAL O VALOR DA MÉDIA CALCULADA E TAMBÉM SE O ALUNO FOI APROVADO OU NÃO.

nota1 = 3.2  
nota2 = 5.4
nota3 = 9.55

media = (nota1+nota2+nota3) / 3
aprovado = media >= 7.0

print(f"a media final e {media}")
print(f"voce foi aprovado {aprovado}")
